# Generated by Django 2.2.1 on 2019-05-18 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippet',
            name='highlighted',
        ),
        migrations.AddField(
            model_name='snippet',
            name='highlight',
            field=models.TextField(default='', verbose_name='高亮演示'),
        ),
    ]
